version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5050:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U theus -d talks"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - talks:/var/lib/postgresql/data:rw

  api:
    container_name: api
    image: node:18.12.0
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app



volumes:
  talks:
    external: true
